### ISSUE TITLE
forest$get_sticks provide empty list

### ISSUE THREAD

**Issue by riccardobergamin** [caravagnalab/rRACES#102]
library(rRACES)

sim <- new(Simulation,
           seed = 468,
           save_snapshot = F
)

sim$duplicate_internal_cells <- T

sim$update_tissue("Liver", 2e3, 2e3)

sim$add_mutant(name = "A",
               epigenetic_rates = c("+-" = 0.01, "-+" = 0.003),
               growth_rates = c("+" = 2,"-" =  1),
               death_rates = c("+" = 0.0, "-" = 0.0))
sim$place_cell("A-", 1e3, 1e3)

sim$run_up_to_time(t = 11)

bbox <- sim$search_sample(c("A+" = 100,"A-" = 100), 50, 50)

sim$sample_cells("Sampling 1", bbox$lower_corner, bbox$upper_corner)

forest <- sim$get_samples_forest()

plot_forest(forest)

forest$get_sticks()

**Comment by albertocasagrande** [comment]
According to the definition of *sticks* (see the documentation [here](https://caravagnalab.github.io/rRACES/reference/SamplesForest-cash-get_sticks.html)):

> A *crucial node* of a forest is a root of the forest, a node whose parent belongs to a different mutant, or the most recent common ancestor of two crucial nodes.
>
> A *stick* is a path of the forest in which the only crucial nodes are the first and the last one.

Since your simulation deals with the single mutant "A" (even though it consists of two species, "A+" and "A-"), the corresponding forest contains no stick.
