### ISSUE TITLE
problem in the installation of rRACES

### ISSUE THREAD

**Issue by AliceAntonello** [caravagnalab/rRACES#56]
Hi, I'm trying to install rRACES but I get the following error 

`fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [CMakeFiles/objlib.dir/src/allele.cpp.o] Error 1
make[2]: *** [CMakeFiles/objlib.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [../_install/lib/libRACES.so] Error 2
ERROR: compilation failed for package ‘rRACES’
* removing ‘/private/var/folders/fw/xs02q7dj3bdbbmpkb4l6hjf40000gn/T/RtmpP9qp3U/Rinst42775b0a6409/rRACES’
      -----------------------------------
ERROR: package installation failed`

I tried both with devtools and cloning the repository, the error remains the same

**Comment by albertocasagrande** [comment]
Which command did you issue?

**Comment by albertocasagrande** [comment]
This is analogue to issue #23. 

In macOS systems, some (old?) R installations force macOSX 10.13 compatibility during package compilation. This request breaks the dependency on the C++17 standard filesystem library `std::filesystem` because the `clang` version distributed with macOSX 10.13 did not support it despite claiming C++17 support.

To solve the issue, remove all the `-mmacosx-version-min=10.13` from the `Makeconf` file (usually in `/Library/Frameworks/R.framework/Resources/etc/Makeconf`).
