### ISSUE TITLE
subclone "imprisoned"

### ISSUE THREAD

**Issue by riccardobergamin** [caravagnalab/rRACES#59]
i am trying to simulate a subclonal expansion with the following code:

``
sim <- new(Simulation, "vaf test",seed = sample(x = 1:1000,size = 1,replace = F),
           save_snapshot = F)
  
  sim$duplicate_internal_cells <- F
  
  sim$update_tissue("Liver", 5e3, 5e3)
  
  sim$add_mutant(name = "A",
                 growth_rates = 1,
                 death_rates = 0)
  
  
  sim$place_cell("A", 2500, 2500)
  
  sim$run_up_to_size("A",1e3)
  
  sim$add_mutant(name = "B",
                 growth_rates = 1.5,
                 death_rates = 0)
  
  sim$mutate_progeny(sim$choose_cell_in("A"), "B")
  
  sim$run_up_to_time(t = 200)

``
but for some reason the subclone B is imprisoned inside the clone A and cannot grow because the model is boundary driven (as in the picture). Can it be related to the function sim$choose_cell_in("A")?

<img width="658" alt="Screenshot 2024-01-17 alle 10 17 04" src="https://github.com/caravagnalab/rRACES/assets/72212720/38c91c92-9c20-4705-bcce-564a6c0a1039">

**Comment by albertocasagrande** [comment]
Commit 134dadd8f703580df9182aa5f6f986e6f27aabe8 introduced a new algorithm for choosing cells when boundary driven growth is used. This was necessary to close issue #55. 

Are you using it?

**Comment by riccardobergamin** [comment]
no,i didn't see it. Should i use choose_border_cell_in()?

**Comment by albertocasagrande** [comment]
No: the new algorithm is used by `choose_cell_in`.

Anyhow, I figured out what was going on. Your model lets $A$ grow to 1000 cells, and $B$ arises. Assuming a circular growth, the border contains $x = \sqrt{1000/\pi} \approx 10*\sqrt{3}$ $A$ cells.  So, when $B$ arises, the probability for $A$ to grow is $10*\sqrt{3}*\frac{\rho_A}{\rho_B}$ times the probability for $B$, where $\rho_A$ and $\rho_B$ are the grow rates of $A$ and $B$, respectively. In our case, $\rho_A=1$ and $\rho_B=1.5$; hence, the probability for $A$ to grow is more than 11 times the probability for $B$, and it is very likely for $A$ to conglobate $B$ eventually. 

The evolution that you have in mind is very unlikely to occur.  Thus, to avoid $B$ conglobation, you have three alternatives:

1. decrease the rate of $A$
2. increase the rate of $B$
3. reduce the mass of $A$ when $B$ arises.

In order to obtain what you have in mind, you may set $\rho_B$ to (for instance) 100, let the system evolve until the number of the cells in $B$ is about that of the cells in $A$, and, finally, update $\rho_B$ to $1.5$.

It could be interesting to have this model as one of the examples of the site to show how to deal with very unlikely situations. What do you think, @caravagn?

**Comment by riccardobergamin** [comment]
ok, i see what you mean. But can we avoid that with some trick? it does not look so impossible to have a driver when A is large, since drivers are rare events, no? here we are considering s = 0.5 as fitness advantage.

**Comment by caravagn** [comment]
This seems a byproduct of the boundary-model that might be related to multiple things

- how the density is calculated around the boundary 
- an overly low probability of dividing far from the boundary

Can I ask: did anybody try to make a model with uniform growth (non-boundary) but sampling on the boundary? Could that solve both the issues of avoiding trapping subclones while giving MRCAs phylogenetically close to the samples cells?

IMHO it is true that 1000 starting cells are not few, but in a generic model those should not be "unbeatable" by the subclone.

**Comment by riccardobergamin** [comment]
i did not try yet. Let's see

**Comment by riccardobergamin** [comment]
![homog](https://github.com/caravagnalab/rRACES/assets/72212720/f5e46b3a-3ac1-4398-a6f0-ece0eeabce97)

**Comment by riccardobergamin** [comment]
i think we should use homogeneous growth for cell counts experiment and boundary driven growth for VAF deconvolution experiment, no? Also other papers about space simulations noticed the challenge to have exponential growth and VAF spectrum in the same simulation
