### ISSUE TITLE
`simulate_seq` time speed-up

### ISSUE THREAD

**Issue by valerianilucrezia** [caravagnalab/rRACES#99]
In the last meeting we talked about enhancing the `simulate_seq` function by simulating the chromosomes in parallel since now it takes ~1day to end.
Furthermore, avoiding the simulation of the mutations below a certain CCF value could speed up the simulation time.

**Comment by caravagn** [comment]
Just to clarify @albertocasagrande :

- let's generate the mutations on each chromosome in paralllel;
- let's add a parameter `CCF_detectability_limit`, default `0.02` so that the algorithm that assigns mutations to a tree will stop as soon as it reaches a cell from which you can reach `n` children (recursively), but in the sample where you sequence those you have `N` total cells and `n/N < CCF_detectability_limit`

Essentially, we determine a depth in the tree where we would ass mutations too rare to be sequenced in the data-generation step.

**Comment by albertocasagrande** [comment]
@valerianilucrezia, to better understand the issue, how much time does rRACES spend building the phylogenetic forest? What is the sequencing coverage? Do you really need to produce the SAM files during this experiment?

What is a CCF?

**Comment by albertocasagrande** [comment]
If your issue is due to the sequencing simulation running time, you may try to distribute the process by chromosome. 

See the `simulate_seq()` and `simulate_normal_seq()`'s parameters `chromosomes` and `update_SAM` introduced by commit 16357cea634ff8a0327102c780a5c174a00e895a. The documentation is available [here](https://caravagnalab.github.io/rRACES/articles/sequencing.html#chromosome-sequencing), [here](https://caravagnalab.github.io/rRACES/articles/sequencing.html#updating-the-sam-output-directory), [here](https://caravagnalab.github.io/rRACES/reference/simulate_seq.html), and [here](https://caravagnalab.github.io/rRACES/reference/simulate_normal_seq.html). 

@valerianilucrezia, please let me know if this solves your issue.

**Comment by jovoni** [comment]
@albertocasagrande I was able to run it in parallel distributing the process by chromosome and the time required definitely decreased

**Comment by valerianilucrezia** [comment]
yes, I confirm that the new implementations reduces the time a lot, thank you!

**Comment by albertocasagrande** [comment]
Closed by commit 16357cea634ff8a0327102c780a5c174a00e895a.
